baseURL: https://iangga.github.io/
languageCode: en-us
title: gawwsu
theme: github.com/adityatelange/hugo-PaperMod

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 10

languages:
  en:
    weight: 1
    contentDir: content/en
  id:
    weight: 2
    contentDir: content/id

markup:
  highlight:
    style: native
